# Generated by Django 5.2.1 on 2025-05-22 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Një përshkrim i shkurtër për përdoruesin.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_url_placeholder',
            field=models.URLField(blank=True, help_text='URL e fotos së profilit (placeholder).', max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(help_text='Rruga dhe numri.', max_length=255)),
                ('city', models.CharField(help_text='Qyteti.', max_length=100)),
                ('state_province', models.CharField(blank=True, help_text='Shteti/Provinca/Rajoni (opsionale).', max_length=100, null=True)),
                ('postal_code', models.CharField(help_text='Kodi postar.', max_length=20)),
                ('country', models.CharField(default='Kosovo', help_text='Shteti.', max_length=100)),
                ('is_default_shipping', models.BooleanField(default=False, help_text='A është kjo adresa primare e dërgesës për përdoruesin?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Përdoruesi të cilit i përket kjo adresë.', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'ordering': ['-is_default_shipping', '-created_at'],
            },
        ),
    ]
