# Generated by Django 5.2.1 on 2025-05-22 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_bio_user_profile_picture_url_placeholder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Emri i llojit të kuzhinës', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Përshkrim i shkurtër (opsional)', null=True)),
            ],
            options={
                'verbose_name': 'Lloj Kuzhine',
                'verbose_name_plural': 'Llojet e Kuzhinave',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Emri i kategorisë së menusë', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Përshkrim i shkurtër (opsional)', null=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Përdoret për të renditur kategoritë në shfaqje')),
            ],
            options={
                'verbose_name': 'Kategori Menuje',
                'verbose_name_plural': 'Kategoritë e Menuve',
                'ordering': ['restaurant', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Emri zyrtar i restorantit', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Përshkrim i detajuar i restorantit', null=True)),
                ('phone_number', models.CharField(help_text='Numri kryesor i telefonit të kontaktit', max_length=20)),
                ('main_image_url_placeholder', models.URLField(blank=True, help_text='URL e fotos kryesore (placeholder)', max_length=512, null=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Vlerësimi mesatar nga klientët', max_digits=3)),
                ('delivery_time_estimate', models.CharField(blank=True, help_text="Koha e përafërt e dërgesës (p.sh., '25-35 min')", max_length=50, null=True)),
                ('price_range', models.CharField(blank=True, choices=[('€', '€ (Lirë)'), ('€€', '€€ (Mesatare)'), ('€€€', '€€€ (Shtrenjtë)')], help_text='Gama e çmimeve', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='A është restoranti aktiv dhe i dukshëm për klientët (menaxhohet nga admini)?')),
                ('is_approved', models.BooleanField(default=False, help_text='A është restoranti i aprovuar nga platforma (menaxhohet nga admini)?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(blank=True, help_text='Adresa kryesore fizike e restorantit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_location', to='api.address')),
                ('cuisine_types', models.ManyToManyField(blank=True, help_text='Llojet e kuzhinës që ofron restoranti', related_name='restaurants', to='api.cuisinetype')),
                ('owner', models.ForeignKey(help_text='Pronari i restorantit (një përdorues me rolin RESTAURANT_OWNER)', on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restorant',
                'verbose_name_plural': 'Restorantet',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Emri i artikullit të menusë', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Përshkrimi i artikullit', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Çmimi i artikullit', max_digits=8)),
                ('image_url_placeholder', models.URLField(blank=True, help_text='URL e fotos së artikullit (placeholder)', max_length=512, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='A është ky artikull aktualisht i disponueshëm për porosi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Kategoria së cilës i përket ky artikull', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.menucategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_menu_items', to='api.restaurant')),
            ],
            options={
                'verbose_name': 'Artikull Menuje',
                'verbose_name_plural': 'Artikujt e Menuve',
                'ordering': ['category__display_order', 'category__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='api.restaurant'),
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'E Hënë'), (2, 'E Martë'), (3, 'E Mërkurë'), (4, 'E Enjte'), (5, 'E Premte'), (6, 'E Shtunë'), (0, 'E Diel')], help_text='Dita e javës')),
                ('open_time', models.TimeField(blank=True, help_text='Ora e hapjes (bosh nëse është mbyllur)', null=True)),
                ('close_time', models.TimeField(blank=True, help_text='Ora e mbylljes (bosh nëse është mbyllur)', null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='A është restoranti i mbyllur gjatë gjithë kësaj dite?')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='api.restaurant')),
            ],
            options={
                'verbose_name': 'Orar Pune',
                'verbose_name_plural': 'Oraret e Punës',
                'ordering': ['restaurant', 'day_of_week'],
                'unique_together': {('restaurant', 'day_of_week')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='menucategory',
            unique_together={('restaurant', 'name')},
        ),
    ]
