# Generated by Django 5.2.1 on 2025-05-22 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cuisinetype_menucategory_restaurant_menuitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address_street', models.CharField(help_text='Rruga e dërgesës', max_length=255)),
                ('delivery_address_city', models.CharField(help_text='Qyteti i dërgesës', max_length=100)),
                ('delivery_address_postal_code', models.CharField(help_text='Kodi postar i dërgesës', max_length=20)),
                ('delivery_address_notes', models.TextField(blank=True, help_text='Shënime shtesë për dërgesën', null=True)),
                ('order_total', models.DecimalField(decimal_places=2, help_text='Shuma totale e porosisë', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Në Pritje'), ('CONFIRMED', 'Konfirmuar'), ('PREPARING', 'Në Përgatitje'), ('READY_FOR_PICKUP', 'Gati për Marrje/Dërgesë'), ('ON_THE_WAY', 'Në Rrugë'), ('DELIVERED', 'Dërguar'), ('CANCELLED_BY_USER', 'Anuluar nga Klienti'), ('CANCELLED_BY_RESTAURANT', 'Anuluar nga Restoranti'), ('FAILED_DELIVERY', 'Dërgesa Dështoi')], db_index=True, default='PENDING', max_length=30)),
                ('payment_method', models.CharField(choices=[('CASH_ON_DELIVERY', 'Para në Dorë'), ('CARD_ONLINE', 'Kartë Online')], default='CASH_ON_DELIVERY', max_length=30)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Në Pritje'), ('PAID', 'Paguar'), ('FAILED', 'Dështuar')], db_index=True, default='PENDING', max_length=20)),
                ('payment_intent_id', models.CharField(blank=True, help_text='ID e pagesës nga procesori (p.sh., Stripe)', max_length=255, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, help_text='Koha e parashikuar e dërgesës', null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, help_text='Koha reale kur u dërgua', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Klienti që bëri porosinë', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, help_text='Shoferi i caktuar për dërgesën (opsional)', limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(help_text='Restoranti nga i cili u porosit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.restaurant')),
            ],
            options={
                'verbose_name': 'Porosi',
                'verbose_name_plural': 'Porositë',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name_at_purchase', models.CharField(help_text='Emri i artikullit në momentin e blerjes', max_length=255)),
                ('item_price_at_purchase', models.DecimalField(decimal_places=2, help_text='Çmimi i artikullit në momentin e blerjes', max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('menu_item', models.ForeignKey(help_text='Artikulli i menusë (mund të jetë fshirë nga menuja)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
            options={
                'verbose_name': 'Artikull Porosie',
                'verbose_name_plural': 'Artikujt e Porosive',
            },
        ),
    ]
