# Generated by Django 5.2.1 on 2025-05-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available_for_delivery',
            field=models.BooleanField(default=False, help_text='A është shoferi aktualisht i disponueshëm për të marrë dërgesa?'),
        ),
    ]
