# Generated by Django 5.2.1 on 2025-05-23 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_menucategory_description_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('user', models.OneToOneField(help_text='Përdoruesi (me rolin DRIVER) të cilit i përket ky profil.', limit_choices_to={'role': 'DRIVER'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='driver_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.CharField(blank=True, help_text='Lloji i mjetit (p.sh., Motor, Makinë, Biçikletë)', max_length=100, null=True)),
                ('license_plate', models.CharField(blank=True, help_text='Targa e mjetit (nëse ka)', max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Shoferi',
                'verbose_name_plural': 'Profilet e Shoferëve',
            },
        ),
    ]
