# Generated by Django 5.2.1 on 2025-05-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_driverprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url_placeholder',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='main_image_url_placeholder',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_url_placeholder',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Fotoja e artikullit të menusë.', null=True, upload_to='menu_item_images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Fotoja kryesore e restorantit.', null=True, upload_to='restaurant_main_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Fotoja e profilit.', null=True, upload_to='profile_pictures/'),
        ),
    ]
