# Generated by Django 5.2.1 on 2025-05-23 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_menuitem_image_url_placeholder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='api.restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Page View Log',
                'verbose_name_plural': 'Restaurant Page View Logs',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Përmbajtja e përgjigjes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.review')),
                ('user', models.ForeignKey(help_text='Përdoruesi që ka bërë përgjigjen (zakonisht pronari i restorantit ose admini)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Përgjigje Vlerësimi',
                'verbose_name_plural': 'Përgjigjet e Vlerësimeve',
                'ordering': ['created_at'],
            },
        ),
    ]
