from django.contrib import admin
from .models import *

admin.site.register(Restaurant)
admin.site.register(Menu)
admin.site.register(MenuItem)
admin.site.register(Order)
admin.site.register(OrderItem)
admin.site.register(Delivery)
admin.site.register(CustomerProfile)
admin.site.register(DriverProfile)
admin.site.register(Payment)
admin.site.register(Review)
admin.site.register(Address)
admin.site.register(Cart)
admin.site.register(CartItem)
admin.site.register(Notification)
admin.site.register(Coupon)
admin.site.register(Transaction)
admin.site.register(Schedule)
admin.site.register(RestaurantCategory)
admin.site.register(MenuCategory)
admin.site.register(FavoriteRestaurant)
admin.site.register(FavoriteItem)
admin.site.register(OpeningHour)
