# Generated by Django 5.2 on 2025-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('DRIVER', 'Driver'), ('ADMIN', 'Admin')], default='CUSTOMER', max_length=10),
        ),
    ]
