# Generated by Django 5.2 on 2025-05-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_openinghours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningHours',
            new_name='OpeningHour',
        ),
    ]
